training_calendar.training_calendar_controller_calendar:
  path: '/training_calendar'
  defaults:
    _controller: '\Drupal\training_calendar\Controller\TrainingCalendarController::calendar'
    _title: 'Training Calendar - Main calendar page'
  requirements:
    _permission: 'tc_access'
training_calendar.training_calendar_controller_refresh_tokens:
  path: '/training_calendar/rest/refresh_tokens'
  defaults:
    _controller: '\Drupal\training_calendar\Controller\TrainingCalendarController::refreshTokens'
    _title: 'Training Calendar - refreshTokens'
  requirements:
      _access: 'TRUE'

training_calendar.training_calendar_controller_trainings:
  path: '/training_calendar/rest/trainings'
  defaults:
    _controller: '\Drupal\training_calendar\Controller\TrainingCalendarController::getTrainings'
    _title: 'Training Calendar - get trainings list'
  requirements:
      _access: 'TRUE'

training_calendar.training_calendar_controller_training_save:
  path: '/training_calendar/rest/training/{id}'
  methods: ['PATCH', 'POST']
  defaults:
    _controller: '\Drupal\training_calendar\Controller\TrainingCalendarController::storeTraining'
    _title: 'Training Calendar - save training'
  requirements:
      _access: 'TRUE'

training_calendar.training_calendar_controller_ping:
  path: '/training_calendar/rest/ping'
  defaults:
    _controller: '\Drupal\training_calendar\Controller\TrainingCalendarController::ping'
    _title: 'Training Calendar - ping'
  requirements:
      _access: 'TRUE'
