training-calendar:
  version: 1.0
  js:
    # Contrib
    /libraries/backbone.modal/backbone.modal-min.js: {}
    /libraries/backform/backform.js: {}
    /libraries/moment/moment.min.js: {}
    /libraries/bluebird/bluebird.min.js: {}
    /libraries/fullcalendar/fullcalendar.min.js: {}

    # CORE Application
    js/training-calendar.js: {}

    # CORE Utilities
    js/utilities/drupal-settings-manager.js: {}
    js/utilities/communication-manager.js: {}
    js/utilities/token-manager.js: {}
    js/utilities/model-manager.js: {}
    js/utilities/view-manager.js: {}

    # Models
    js/models/TrainingModel.js: {}

    # Views
    js/views/TrainingView.js: {}
    js/views/TrainingEdit.js: {}

  css:
    theme:
      # Contrib
      /libraries/fullcalendar/fullcalendar.css: {}
      /libraries/backbone.modal/backbone.modal.css: {}
      /libraries/backbone.modal/backbone.modal.theme.css: {}


      # CORE Application
      css/style.css: {}

  dependencies:
    - core/drupal
    - core/drupalSettings
    - core/backbone
    - core/jquery
    - core/jquery.once
    - core/matchmedia
    - core/matchmedia.addListener


