services:
  #D8 Core services: https://api.drupal.org/api/drupal/core%21core.services.yml/8.2.x
  training_calendar.oauth2.token_manager:
    class: Drupal\training_calendar\Oauth2\TokenManager
    arguments:
      - '@request_stack'
      - '@plugin.manager.oauth2_grant.processor'
      - '@simple_oauth.repositories.user'
      - '@simple_oauth.repositories.refresh_token'
      - '@config.factory'
