<?php

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * @param string $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *
 * @return string
 */
function training_calendar_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.training_calendar':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Training Calendar for runners...') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_theme().
 *
 * create one for each theme (twig file)
 */
function training_calendar_theme() {
  return [
    'training_calendar_calendar' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
  ];
}
