<?php

use Drupal\Core\Routing\RouteMatchInterface;
use \Drupal\Core\Form\FormStateInterface;
use \Drupal\Core\TempStore\PrivateTempStoreFactory;
use \Drupal\Core\TempStore\PrivateTempStore;

/**
 * @param string $route_name
 * @param \Drupal\Core\Routing\RouteMatchInterface $route_match
 *
 * @return string
 */
function training_calendar_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.training_calendar':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Training Calendar for runners...') . '</p>';
      return $output;

    default:
      return null;
  }
}

/**
 * @param array $page
 */
function training_calendar_page_attachments_alter(array &$page)
{
  if (!\Drupal::currentUser()->hasPermission('tc_access'))
  {
    return;
  }

  //@todo: check if we are on the correct url

  //@this is for basic auth - let's implement oauth2
  $username = "AAA";
  $password = "BBB";
  $usrPwd = $username . ':' . $password;
  $userhash = base64_encode($usrPwd);
  $page['#attached']['drupalSettings']['training_calendar']['userhash'] = $userhash;
}

/**
 * Implements hook_theme().
 *
 * create one for each theme (twig file)
 */
function training_calendar_theme() {
  return [
    'training_calendar_calendar' => [
      'variables' => [
        'content' => NULL,
      ],
    ],
  ];
}
