training_calendar.training_calendar_controller_calendar:
  path: '/training_calendar'
  defaults:
    _controller: '\Drupal\training_calendar\Controller\TrainingCalendarController::calendar'
    _title: 'Training Calendar - Main calendar page'
  requirements:
    _permission: 'tc_access'
training_calendar.training_calendar_controller_ping:
  path: '/training_calendar/rest/ping'
  defaults:
    _controller: '\Drupal\training_calendar\Controller\TrainingCalendarController::ping'
    _title: 'Training Calendar - ping'
  requirements:
      _access: 'TRUE'
